package game.service.factories;

import java.util.Random;

import game.model.Player;
import game.model.board.spaces.DrawCardSpace;
import game.model.board.spaces.Space;
import game.model.board.spaces.TreasureSpace;
import game.model.board.spaces.VillageSpace;

public class SpaceFactory {
  private static final Random random = new Random();

  /**
   * The function `createRandomSpace` generates a random type of space based on a dice roll percentage.
   * 
   * @param id The `id` parameter is an integer value that is used to uniquely identify the space being
   * created. It is passed to the constructor of the `DrawCardSpace` to create a unique name for the
   * space, such as "Mysterious Woods 1", "Mysterious Woods 2", and so
   * @return The method `createRandomSpace` returns an instance of a subclass of the `Space` class
   * based on a random roll generated by the `random.nextInt(100)` method. The specific subclass
   * instance returned depends on the value of the random roll:
   */
  public static Space createRandomSpace(int id) {
    int roll = random.nextInt(100);

    if (roll < 40) {
      return new Space("Plain", "A quiet and lonely walk") {
        @Override
        public void onLand(Player player) {
          System.out.println("Nothing happens, you take a breath of fresh air.");
        }
      };

    } else if (roll < 75) {
      return new DrawCardSpace("Mysterious Woods " + id, "The shadows lengthen around you...");
    } else if (roll < 90) {
      return new TreasureSpace();
    } else {
      return new VillageSpace();
    }
  }
}
